Add a more clear message that the script didn't die.

diff --git a/icpc-wf/disable-turboboost_ht b/icpc-wf/disable-turboboost_ht
--- a/icpc-wf/disable-turboboost_ht
+++ b/icpc-wf/disable-turboboost_ht
@@ -31,7 +31,7 @@ done
 DIR=/sys/devices/system/cpu/intel_pstate
 if [ -d $DIR ]; then
 	# now disable turbo boost
-	echo -n 1 > $DIR/no_turbo || true
+	echo -n 1 > $DIR/no_turbo || echo "Could not write to '$DIR/no_turbo', ignoring for now..."
 	if [ $(cat $DIR/no_turbo) -ne 1 ]; then
 		echo "Error: turboboost still enabled!"
 		exit 1
